name: 'AppRunner Status Listener'
description: 'Wait for AppRunner`s specific status'
inputs:
  aws-access-key-id:
    description: 'AWS Authentication Data'
    required: true
  aws-secret-access-key:
    description: 'AWS Authentication Data'
    required: true
  aws-region:
    description: 'AWS Authentication Data'
    required: true
  app-arn:
    description: 'AppRunner service ARN'
    required: true
  desired-status:
    description: 'Desired AppRunner service status, validated against official documentation at https://docs.aws.amazon.com/apprunner/latest/api/API_Service.html'
    required: true
  sleep-time:
    description: 'Sleep time between requests to the AWS API in ms'
    default: '5000'
  timeout:
    description: 'Timeout in ms. `0` means no timeout'
    default: '30000'
outputs:
  timed-out:
    description: '`true` if the desired status wasn`t received before the timeout occurred'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'yellow'
  
